# REQUEST FOR TESTING STUFF

GET {{host}}/fetch
[QueryStringParams]
issys_name:
issys_kernelv: 
issys_hostname: 
issys_osv: 
issys_osvlong: 
issys_uptime:
issys_distroid: 1
ismnt_drive: /
ismnt_drive: /boot

GET {{host}}/fetch
[QueryStringParams]
ihram_totalmem: 1
ihram_usedmem: 1
ihram_freemem: 1
ihram_availmem: 1
ihram_totalswp: 1
ihram_freeswp: 1
ihram_usedswp: 1

GET {{host}}/fetch
[QueryStringParams]
ihcpu_name: 1
ihcpu_cores: 1
